{{- with index .Values "secrets" "elasticsearch" }}
{{- range $ns := .namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $ns }}
type: Opaque
data:
  username: {{ "elastic" | b64enc }}
  password: {{ .password | b64enc | quote }}
{{- end }}
---
{{- end }}