{{- with index .Values "secrets" "elasticsearch" }}
{{- $name := .name | quote }}
{{- $password := .password | b64enc | quote }}
{{- range $ns := .namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $ns }}
type: Opaque
data:
  username: "elastic"
  password: {{ $password }}
{{- end }}
---
{{- end }}